const arrayFighter = [1, 32];
console.log(arrayFighter);
arrayFighter.push('Tank');
console.log(arrayFighter);
arrayFighter.pop();
console.log(arrayFighter);
arrayFighter.shift('Fighter');
console.log(arrayFighter);
arrayFighter[Array.length] = 'fighter';
console.log(arrayFighter);